// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upidbheojdwxpuxczrhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaWRiaGVvamR3eHB1eGN6cmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODEwOTYsImV4cCI6MjA2NjE1NzA5Nn0.s84UWmZtsiCwNMNbPGhCoAstPqLHs31Rj_wO6LZ_wr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);